# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "849167d7e53096af4c222842c24e14af"
name = "POPDECKS"
handle = "popdecks"
application_url = "https://lb-panic-referrals-tom.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_cart_transforms,read_checkout_branding_settings,read_content,read_customer_events,read_customer_merge,read_customers,read_delivery_customizations,read_discounts,read_draft_orders,read_files,read_fulfillments,read_gift_cards,read_inventory,read_legal_policies,read_locales,read_locations,read_marketing_events,read_merchant_managed_fulfillment_orders,read_online_store_pages,read_orders,read_price_rules,read_products,read_publications,read_reports,read_resource_feedbacks,read_script_tags,read_shipping,read_shopify_payments_disputes,read_shopify_payments_payouts,read_themes,read_third_party_fulfillment_orders,write_assigned_fulfillment_orders,write_cart_transforms,write_checkout_branding_settings,write_content,write_customer_merge,write_customers,write_delivery_customizations,write_discounts,write_draft_orders,write_files,write_fulfillments,write_gift_cards,write_inventory,write_locales,write_locations,write_marketing_events,write_merchant_managed_fulfillment_orders,write_orders,write_pixels,write_price_rules,write_products,write_publications,write_reports,write_resource_feedbacks,write_script_tags,write_shipping,write_themes,write_third_party_fulfillment_orders"

[auth]
redirect_urls = ["https://lb-panic-referrals-tom.trycloudflare.com/auth/callback", "https://lb-panic-referrals-tom.trycloudflare.com/auth/shopify/callback", "https://lb-panic-referrals-tom.trycloudflare.com/api/auth/callback"]

[app_proxy]
url = "https://lb-panic-referrals-tom.trycloudflare.com/proxy"
subpath = "optistep-2"
prefix = "apps"

[pos]
embedded = false
